In [1]:
import numpy as np
dat = np.array([[56,1,4],[35,42,3],[1,56,34]])

In [2]:
sum_dat = dat.sum(axis=0)

In [3]:
print(sum_dat)

[92 99 41]


In [4]:
percentage = 100 * dat/sum_dat
print(percentage)

[[60.86956522  1.01010101  9.75609756]
 [38.04347826 42.42424242  7.31707317]
 [ 1.08695652 56.56565657 82.92682927]]


BroadCasting in a different way

In [5]:
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])

In [6]:
c = a + b
print(c)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


This should have thrown an error but due to numpy arrays broadcasting properties the both matrces expanded and added.
Keep this in mind to not to run into errors.

In [9]:
a = [[1]]
b = np.array(a)
print(b)
c = int(b) * 2
print(c)

[[1]]
2
